[package]
name = "no-bundler-mpa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
askama = "0.10"
actix-files = "0.5"
serde = { version = "1.0", features = ["derive"] }